import 'package:flutter/widgets.dart';

class ZeroIcons {
  ZeroIcons._();

  static const _kFontFam = 'ZeroIcons';
  static const String _kFontPkg = 'zero_ui_mobile';

  static const IconData accountBook =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aim =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apartment =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData api =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appstoreAdd =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audioMuted =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appstore =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audio =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audit =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bars =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData borderlessTable =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bug =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData branches =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData build =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bulb =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carryOut =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ciCircle =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ci =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudDownload =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudServer =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudSync =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudUpload =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cluster =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compress =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData consoleSql =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contacts =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData container =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copyrightCircle =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copyright =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creditCard =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customerService =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deleteColumn =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deleteRow =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deliveredProcedure =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deploymentUnit =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dingtalk =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disconnect =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislike =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollarCircle =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipsis =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData environment =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData euroCircle =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData euro =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exception =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expandAlt =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appExport =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData experiment =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeInvisible =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fieldBinary =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fieldNumber =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fieldString =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fieldTime =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileAdd =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileDone =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileExcel =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileExclamation =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileGif =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileImage =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileJpg =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileMarkdown =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filePdf =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileProtect =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileSearch =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filePpt =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileSync =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileText =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileUnknown =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileZip =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileWord =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderAdd =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderOpen =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderView =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fork =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData formatPainter =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frown =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData function =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fundProjectionScreen =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fundView =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData funnelPlot =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gateway =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gif =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData global =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gold =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hdd =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idcard =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appImport =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insertRowAbove =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insertRowBelow =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insertRowLeft =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insertRowRight =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insurance =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData interaction =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layout =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loading =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loading3Quarters =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData macCommand =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail =
      IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData man =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medicineBox =
      IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meh =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mergeCells =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message =
      IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moneyCollect =
      IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitor =
      IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more =
      IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData node =
      IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nodeCollapse =
      IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nodeExpand =
      IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification =
      IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number =
      IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oneToOne =
      IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paperClip =
      IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData partition =
      IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payCircle =
      IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percentage =
      IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone =
      IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture =
      IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playSquare =
      IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poundCircle =
      IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pound =
      IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poweroff =
      IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData printer =
      IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile =
      IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project =
      IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData propertySafety =
      IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pullRequest =
      IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pushpin =
      IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode =
      IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData read =
      IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reconciliation =
      IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redEnvelope =
      IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reload =
      IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rest =
      IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData robot =
      IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rocket =
      IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotateLeft =
      IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotateRight =
      IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData safetyCertificate =
      IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData safety =
      IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save =
      IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan =
      IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule =
      IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search =
      IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData securityScan =
      IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData select =
      IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send =
      IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting =
      IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shake =
      IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shareAlt =
      IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop =
      IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoppingCart =
      IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping =
      IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sisternode =
      IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skin =
      IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile =
      IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solution =
      IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound =
      IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData splitCells =
      IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subnode =
      IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switcher =
      IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appSync =
      IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table =
      IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet =
      IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tags =
      IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData team =
      IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thunderbolt =
      IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toTop =
      IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tool =
      IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trademarkCircle =
      IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trademark =
      IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction =
      IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData translation =
      IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy =
      IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ungroup =
      IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock =
      IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload =
      IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usb =
      IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userAdd =
      IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userDelete =
      IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userSwitch =
      IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usergroupAdd =
      IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usergroupDelete =
      IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified =
      IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videoCameraAdd =
      IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videoCamera =
      IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet =
      IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsApp =
      IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi =
      IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData woman =
      IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alibaba =
      IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alipayCircle =
      IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alipay =
      IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aliwangwang =
      IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aliyun =
      IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amazon =
      IconData(0xe8f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android =
      IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData antCloud =
      IconData(0xe8f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData antDesign =
      IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple =
      IconData(0xe8f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behanceSquare =
      IconData(0xe8f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behance =
      IconData(0xe8f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chrome =
      IconData(0xe8fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codeSandbox =
      IconData(0xe8fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codepenCircle =
      IconData(0xe8fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codepen =
      IconData(0xe8fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dingding =
      IconData(0xe8fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbbleSquare =
      IconData(0xe8ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropbox =
      IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github =
      IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook =
      IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gitlab =
      IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googlePlus =
      IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google =
      IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData html5 =
      IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram =
      IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin =
      IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mediumWorkmark =
      IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ie =
      IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium =
      IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit =
      IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qq =
      IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sketch =
      IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype =
      IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slackSquare =
      IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slack =
      IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taobaoCircle =
      IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taobao =
      IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter =
      IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wechat =
      IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weiboCircle =
      IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weiboSquare =
      IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weibo =
      IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windows =
      IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yahoo =
      IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube =
      IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yuque =
      IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zhihu =
      IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barChart =
      IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData areaChart =
      IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxPlot =
      IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dotChart =
      IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fall =
      IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fund =
      IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heatMap =
      IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lineChart =
      IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pieChart =
      IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radarChart =
      IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliders =
      IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rise =
      IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stock =
      IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowDown =
      IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowLeft =
      IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowRight =
      IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowUp =
      IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowsAlt =
      IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward =
      IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData borderBottom =
      IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData borderHorizontal =
      IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData borderInner =
      IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData borderLeft =
      IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData borderOuter =
      IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData borderRight =
      IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData borderTop =
      IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData borderVerticle =
      IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caretDown =
      IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caretLeft =
      IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caretRight =
      IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doubleLeft =
      IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doubleRight =
      IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caretUp =
      IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downCircle =
      IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downSquare =
      IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down =
      IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enter =
      IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fastBackward =
      IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fastForward =
      IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward =
      IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leftCircle =
      IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fullscreenExit =
      IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fullscreen =
      IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leftSquare =
      IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left =
      IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login =
      IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout =
      IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuFold =
      IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuUnfold =
      IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picCenter =
      IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picLeft =
      IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picRight =
      IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playCircle =
      IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radiusBottomLeft =
      IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radiusBottomRight =
      IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radiusUpLeft =
      IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radiusUpright =
      IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retweet =
      IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rightCircle =
      IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rightSquare =
      IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right =
      IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rollback =
      IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shrink =
      IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stepBackward =
      IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stepForward =
      IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swapLeft =
      IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swapRight =
      IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swap =
      IconData(0xe962, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upCircle =
      IconData(0xe963, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upSquare =
      IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up =
      IconData(0xe965, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verticalAlignMiddle =
      IconData(0xe966, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verticalAlignBottom =
      IconData(0xe967, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verticalAlignTop =
      IconData(0xe968, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verticalLeft =
      IconData(0xe969, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verticalRight =
      IconData(0xe96a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alignCenter =
      IconData(0xe96b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alignLeft =
      IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bgColors =
      IconData(0xe96d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold =
      IconData(0xe96e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alignRight =
      IconData(0xe96f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData columnHeight =
      IconData(0xe970, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData columnWidth =
      IconData(0xe971, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy =
      IconData(0xe972, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dash =
      IconData(0xe973, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete =
      IconData(0xe974, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff =
      IconData(0xe975, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drag =
      IconData(0xe976, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit =
      IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fontColors =
      IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fontSize =
      IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData form =
      IconData(0xe97a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData highlight =
      IconData(0xe97b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic =
      IconData(0xe97c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lineHeight =
      IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orderedList =
      IconData(0xe97e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radiusSetting =
      IconData(0xe97f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo =
      IconData(0xe980, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scissor =
      IconData(0xe981, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smallDash =
      IconData(0xe982, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snippets =
      IconData(0xe983, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sortAscending =
      IconData(0xe984, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sortDescending =
      IconData(0xe985, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strikeThrough =
      IconData(0xe986, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData underline =
      IconData(0xe987, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo =
      IconData(0xe988, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unorderedList =
      IconData(0xe989, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoomOut =
      IconData(0xe98a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoomIn =
      IconData(0xe98b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkSquare =
      IconData(0xea21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkCircle =
      IconData(0xea22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clockCircle =
      IconData(0xea23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check =
      IconData(0xea24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closeSquare =
      IconData(0xea25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closeCircle =
      IconData(0xea26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close =
      IconData(0xea27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamationCircle =
      IconData(0xea28, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infoCircle =
      IconData(0xea29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation =
      IconData(0xea2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info =
      IconData(0xea2b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData issueClose =
      IconData(0xea2c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minusCircle =
      IconData(0xea2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minusSquare =
      IconData(0xea2e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus =
      IconData(0xea2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pauseCircle =
      IconData(0xea30, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plusCircle =
      IconData(0xea31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause =
      IconData(0xea32, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plusSquare =
      IconData(0xea33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      IconData(0xea34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData questionCircle =
      IconData(0xea35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question =
      IconData(0xea36, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop =
      IconData(0xea37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning =
      IconData(0xea38, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  // Filled Variant
  static const IconData accountBookFilled =
      IconData(0xe98c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alipaySquareFilled =
      IconData(0xe98d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alertFilled =
      IconData(0xe98e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amazonCircleFilled =
      IconData(0xe98f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amazonSquareFilled =
      IconData(0xe990, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apiFilled =
      IconData(0xe991, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appstoreFilled =
      IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audioFilled =
      IconData(0xe993, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bankFilled =
      IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bellFilled =
      IconData(0xe995, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behanceCircleFilled =
      IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookFilled =
      IconData(0xe997, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bugFilled =
      IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buildFilled =
      IconData(0xe999, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bulbFilled =
      IconData(0xe99a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculatorFilled =
      IconData(0xe99b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarFilled =
      IconData(0xe99c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carFilled =
      IconData(0xe99d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carryOutFilled =
      IconData(0xe99e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ciCircleFilled =
      IconData(0xe99f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudFilled =
      IconData(0xe9a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codeFilled_1 =
      IconData(0xe9a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codeFilled =
      IconData(0xe9a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codeSandboxSquareFilled =
      IconData(0xe9a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codepenSquareFilled =
      IconData(0xe9a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compassFilled =
      IconData(0xe9a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contactsFilled =
      IconData(0xe9a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData containerFilled =
      IconData(0xe9a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData controlFilled =
      IconData(0xe9a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copyrightCircleFilled =
      IconData(0xe9a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creditCardFilled =
      IconData(0xe9aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crownFilled =
      IconData(0xe9ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customerServiceFilled =
      IconData(0xe9ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboardFilled =
      IconData(0xe9ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData databaseFilled =
      IconData(0xe9ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dingtalkCircleFilled =
      IconData(0xe9af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dingtalkSquareFilled =
      IconData(0xe9b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislikeFilled =
      IconData(0xe9b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollarCircleFilled =
      IconData(0xe9b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbbleCircleFilled =
      IconData(0xe9b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropboxCircleFilled =
      IconData(0xe9b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropboxSquareFilled =
      IconData(0xe9b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData environmentFilled =
      IconData(0xe9b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData euroCircleFilled =
      IconData(0xe9b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData experimentFilled =
      IconData(0xe9b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeFilled =
      IconData(0xe9b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeInvisibleFilled =
      IconData(0xe9ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileAddFilled =
      IconData(0xe9bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileExclamationFilled =
      IconData(0xe9bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileExcelFilled =
      IconData(0xe9bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileFilled =
      IconData(0xe9be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileImageFilled =
      IconData(0xe9bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileMarkdownFilled =
      IconData(0xe9c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filePdfFilled =
      IconData(0xe9c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filePptFilled =
      IconData(0xe9c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileTextFilled =
      IconData(0xe9c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileUnknownFilled =
      IconData(0xe9c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileWordFilled =
      IconData(0xe9c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileZipFilled =
      IconData(0xe9c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filterFilled =
      IconData(0xe9c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fireFilled =
      IconData(0xe9c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flagFilled =
      IconData(0xe9c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderAddFilled =
      IconData(0xe9ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderFilled =
      IconData(0xe9cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderOpenFilled =
      IconData(0xe9cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData formatPainterFilled =
      IconData(0xe9cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frownFilled =
      IconData(0xe9ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData funnelPlotFilled =
      IconData(0xe9cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData giftFilled =
      IconData(0xe9d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goldFilled =
      IconData(0xe9d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goldenFilled =
      IconData(0xe9d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleCircleFilled =
      IconData(0xe9d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googlePlusCircleFilled =
      IconData(0xe9d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googlePlusSquareFilled =
      IconData(0xe9d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleSquareFilled =
      IconData(0xe9d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hddFilled =
      IconData(0xe9d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartFilled =
      IconData(0xe9d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeFilled =
      IconData(0xe9d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglassFilled =
      IconData(0xe9da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idcardFilled =
      IconData(0xe9db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ieCircleFilled =
      IconData(0xe9dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ieSquareFilled =
      IconData(0xe9dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insuranceFilled =
      IconData(0xe9de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData interactionFilled =
      IconData(0xe9df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layoutFilled =
      IconData(0xe9e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData likeFilled =
      IconData(0xe9e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lockFilled =
      IconData(0xe9e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData macCommandFilled =
      IconData(0xe9e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mailFilled =
      IconData(0xe9e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medicineBoxFilled =
      IconData(0xe9e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mediumCircleFilled =
      IconData(0xe9e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mediumSquareFilled =
      IconData(0xe9e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mehFilled =
      IconData(0xe9e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messageFilled =
      IconData(0xe9e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobileFilled =
      IconData(0xe9ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationFilled =
      IconData(0xe9eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moneyCollectFilled =
      IconData(0xe9ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payCircleFilled =
      IconData(0xe9ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phoneFilled =
      IconData(0xe9ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pictureFilled =
      IconData(0xe9ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playSquareFilled =
      IconData(0xe9f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poundCircleFilled =
      IconData(0xe9f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData printerFilled =
      IconData(0xe9f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profileFilled =
      IconData(0xe9f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData projectFilled =
      IconData(0xe9f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData propertySafetyFilled =
      IconData(0xe9f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pushpinFilled =
      IconData(0xe9f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qqCircleFilled =
      IconData(0xe9f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qqSquareFilled =
      IconData(0xe9f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData readFilled =
      IconData(0xe9f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reconciliationFilled =
      IconData(0xe9fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redEnvelopeFilled =
      IconData(0xe9fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redditCircleFilled =
      IconData(0xe9fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redditSquareFilled =
      IconData(0xe9fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restFilled =
      IconData(0xe9fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData robotFilled =
      IconData(0xe9ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rocketFilled =
      IconData(0xea00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData safetyCertificateFilled =
      IconData(0xea01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saveFilled =
      IconData(0xea02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scheduleFilled =
      IconData(0xea03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData securityScanFilled =
      IconData(0xea04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingFilled =
      IconData(0xea05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopFilled =
      IconData(0xea06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoppingFilled =
      IconData(0xea07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signalFilled =
      IconData(0xea08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sketchCircleFilled =
      IconData(0xea09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sketchSquareFilled =
      IconData(0xea0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skinFilled =
      IconData(0xea0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slackCircleFilled =
      IconData(0xea0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smileFilled =
      IconData(0xea0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundFilled =
      IconData(0xea0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData starFilled =
      IconData(0xea0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switcherFilled =
      IconData(0xea10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tabletFilled =
      IconData(0xea11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tagFilled =
      IconData(0xea12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tagsFilled =
      IconData(0xea13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taobaoSquareFilled =
      IconData(0xea14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thunderboltFilled =
      IconData(0xea15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toolFilled =
      IconData(0xea16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trademarkCircleFilled =
      IconData(0xea17, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophyFilled =
      IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitterCircleFilled =
      IconData(0xea19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitterSquareFilled =
      IconData(0xea1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlockFilled =
      IconData(0xea1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usbFilled =
      IconData(0xea1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videoCameraFilled =
      IconData(0xea1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walletFilled =
      IconData(0xea1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zhihuCircleFilled =
      IconData(0xea1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zhihuSquareFilled =
      IconData(0xea20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
